import { LanguageLabel, ProjectFilter, Tool, Languages } from '@/types';
import { MonitorCog, Gpu, TabletSmartphone, Lightbulb } from 'lucide-react';

// Tools/Tech Stack
export const tools:Tool[] = [
  { id: 'js', name: 'Javascript', icon: 'javascript.png', category: 'language', selected: false, details: '', projects: ['AiChat', 'Suma'] },
  { id: 'ts', name: 'TypeScript', icon: 'typescript.svg', category: 'language', selected: false, details: '', projects: ['AiChat', 'Suma'] },
  { id: 'svelte', name: 'SvelteKit', icon: 'svelte.svg', category: 'framework', selected: false, details: '', projects: ['AiChat', 'Suma'] },
  { id: 'next', name: 'Next.JS', icon: 'nextjs.png', category: 'framework', selected: false, details: '2 years Experience, used for both as a Frontend and Fullstack. familiar with App Router, with integration with Tanstack Query, Zustand, Drizzle ORM, and Docker.', projects: ['AiChat', 'Suma'] },
  { id: 'react', name: 'React.JS', icon: 'reactjs-square.png', category: 'framework', selected: false, details: '', projects: ['AiChat', 'Suma'] },
  { id: 'zustand', name: 'Zustand', icon: 'zustand.jpeg', category: 'state', selected: false, details: '', projects: ['AiChat', 'Suma'] },
  { id: 'tanstack', name: 'Tanstack', icon: 'tanstack.png', category: 'tools', selected: false, details: '', projects: ['AiChat', 'Suma'] },
  { id: 'postgres', name: 'PostgreSQL', icon: 'postgresql.png', category: 'database', selected: false, details: '', projects: ['AiChat', 'Suma'] },
  { id: 'mysql', name: 'MySQL', icon: 'mysql.png', category: 'database', selected: false, details: '', projects: ['AiChat', 'Proedu', 'Energy Logistics']},
  { id: 'drizzle', name: 'Drizzle', icon: 'drizzle.png', category: 'orm', selected: false, details: '', projects: ['AiChat', 'Suma'] },
  { id: 'docker', name: 'Docker', icon: 'docker.webp', category: 'devops', selected: false, details: '', projects: ['AiChat', 'Suma'] },
  { id: 'nest', name: 'Nest.JS', icon: 'nestjs.png', category: 'backend', selected: false, details: '', projects: ['AiChat', 'Suma'] },
  { id: 'expo', name: 'React Expo', icon: 'expo.png', category: 'mobile', selected: false, details: 'React Native Framework to create mobile app using React. very helpful since it also provide development build app and other usefull function like OTA update and EAS', projects: ['AiChat', 'Proedu'] },
  { id: 'tailwind', name: 'Tailwind CSS', icon: 'tailwind.png', category: 'frontend', selected: false, details: '', projects: ['AiChat', 'Suma', 'Energy Logistics']},
  { id: 'bootstrap', name: 'Bootstrap', icon: 'bootstrap.png', category: 'frontend', selected: false, details: '', projects: ['AiChat', 'Suma', 'Energy Logistics']},
  { id: 'mantine', name: 'Mantine', icon: 'mantine.png', category: 'frontend', selected: false, details: '', projects: ['AiChat', 'Suma', 'Energy Logistics']},
  { id: 'heroui', name: 'Hero UI', icon: 'hero-ui.webp', category: 'frontend', selected: false, details: '', projects: ['Suma']},
  { id: 'laravel', name: 'Laravel', icon: 'laravel.jpeg', category: 'framework', selected: false, details: '', projects: ['AiChat', 'Suma'] },
  { id: 'ci', name: 'Codeigniter', icon: 'codeigniter.png', category: 'framework', selected: false, details: '', projects: ['Energy Logistics', 'Proedu', 'Izistay']},
  { id: 'jquery', name: 'jQuery', icon: 'jquery2.svg', category: 'frontend', selected: false, details: '', projects: ['Energy Logistics', 'Izistay', 'Proedu']},
  { id: 'alpine', name: 'Alpine JS', icon: 'alpinejs.png', category: 'frontend', selected: false, details: '', projects: ['Energy Logistics']},
  { id: 'socketio', name: 'Socket.IO', icon: 'socket-io.svg', category: 'websocket', selected: false, details: 'Websocket Library', projects: ['AiChat']},
  { id: 'zod', name: 'zod', icon: 'zod.jpeg', category: 'library', selected: false, details: 'Typescript Schema Validation', projects: ['AiChat']},
  { id: 'formik', name: 'Formik', icon: 'formik.png', category: 'library', selected: false, details: 'Form Handling Library', projects: ['AiChat']},
  { id: 'react-hook-form', name: 'React Hook Form', icon: 'react-hook-form.png', category: 'library', selected: false, details: 'Form Handling Library', projects: ['Suma']},
  { id: 'vite', name: 'Vite', icon: 'vite.png', category: 'library', selected: false, details: '', projects: ['AiChat']},
  { id: 'prisma', name: 'Prisma ORM', icon: 'prisma.webp', category: 'orm', selected: false, details: '', projects: ['Suma']},
];

// Translations
export const translations:Languages = {
  EN: {
    myWorks: "My Works",
    contactMe: "Contact Me",
    downloadCV: "Download CV",
    title: "Website Developer for 7 years.",
    subtitle: "ready to transform and grow your business together",
    name: "Akbar Rizkianto",
    roles: [
      {
        title: "Frontend",
        icon: Gpu,
      },
      {
        title: "Software Engineer",
        icon: MonitorCog,
      },
      {
        title: "Product Maker",
        icon: Lightbulb,
      },
    ],
    location: "Indonesia (Bogor)",
    tagline: "Am I the one you are looking for? Quickly find that out!",
    agentDescription: "Please provide clear and detailed information for better result",
    writeDescription: "Write description",
    sampleAgentValue: "example: Required Frontend web developer with 2 years experience, used for both as a Frontend and Fullstack. familiar with App Router, with integration with Tanstack Query, Zustand, Drizzle ORM, and Docker.",
    uploadJobPoster: "Upload job poster",
    pasteLink: "Paste Link",
    requirementPlaceholder: "Paste your requirement here...",
    requirementHelp: "don't know what exactly you are looking for? or you need help to define the requirement? I have created one tools to help you out, check here!",
    analyzeProfile: "Analyze Profile",
    toolsTitle: "The Tools of My Craft",
    toolsSubtitle: "select one or more tools to find out more details",
    projects: "Experience Milestone",
    all: "All",
    companyRoles: "Company & Roles",
    taskResponsibility: "Task & Responsibility",
    portfolio: "Portfolio",
    fulltime: "Fulltime Employee",
    contract: "Contract employee",
    freelance: "Freelance",
    remote: "Remote",
    officialActive: "Official Link (Active)",
    officialInactive: "Official Link (Inactive)",
    tribute: "Tribute",
    nextExperience: "2 years Experience, used for both as a Frontend and Fullstack. familiar with App Router, with integration with Tanstack Query, Zustand, Drizzle ORM, and Docker.",
    shipmentTracking: "SHIPMENT TRACKING"
  },
  ID: {
    myWorks: "Karya Saya",
    contactMe: "Hubungi Saya",
    downloadCV: "Unduh CV",
    title: "Pembuat Website selama 7 tahun.",
    subtitle: "siap untuk membantu digitalisasi bisnis Anda!",
    name: "Akbar Rizkianto",
    roles: [
      {
        title: "Front End",
        icon: Gpu,
      },
      {
        title: "Software Engineer",
        icon: MonitorCog,
      },
      {
        title: "Product Maker",
        icon: Lightbulb,
      },
    ],
    location: "Indonesia (Bogor)",
    tagline: "Apakah saya orang yang anda cari? Cepat cek sekarang!",
    agentDescription: "Tulis deskripsi sejelas mungkin untuk hasil yang lebih baik",
    writeDescription: "Tulis deskripsi",
    sampleAgentValue: "example: Required Frontend web developer with 2 years experience, used for both as a Frontend and Fullstack. familiar with App Router, with integration with Tanstack Query, Zustand, Drizzle ORM, and Docker.",
    uploadJobPoster: "Unggah poster pekerjaan",
    pasteLink: "Tempel Tautan",
    requirementPlaceholder: "Tempel kebutuhan Anda di sini...",
    requirementHelp: "tidak tahu persis apa yang Anda cari? atau butuh bantuan untuk mendefinisikan kebutuhan? Saya telah membuat alat untuk membantu Anda, cek di sini!",
    analyzeProfile: "Analisis Profil",
    toolsTitle: "Alat-alat Keahlian Saya",
    toolsSubtitle: "pilih satu atau lebih tools untuk mengetahui detail lebih lanjut",
    projects: "Pengalaman Kerja",
    all: "Semua",
    companyRoles: "Perusahaan & Peran",
    taskResponsibility: "Tugas & Tanggung Jawab",
    portfolio: "Portofolio",
    fulltime: "Karyawan Tetap",
    contract: "Karyawan Kontrak",
    freelance: "Freelance",
    remote: "Remote",
    officialActive: "Link Resmi (Aktif)",
    officialInactive: "Link Resmi (Tidak Aktif)",
    tribute: "Tribute",
    nextExperience: "Digunakan selama 2 tahun, pengalaman pertama saat bekerja di AiChat sering menggunakan app router, memiliki pengalaman menggunakannya sebagai FullStack mandiri atau sebagai Tech Stack Frontend khusus.",
    shipmentTracking: "PELACAKAN PENGIRIMAN"
  }
};