import { ContentLabels, ProjectFilter, Tool } from '@/types';
import { MonitorCog, Gpu, TabletSmartphone, Lightbulb } from 'lucide-react';

// Tools/Tech Stack
export const tools: Tool[] = [
  { id: 'js', name: 'Javascript', icon: 'javascript.png', category: 'programming language', section: 'Frontend', selected: false, details: 'Dynamic programming language for web development and interactive user interfaces.', projects: ['AiChat', 'Proedu', 'Izistay', 'Sumaplafon', 'Energy Logistics'] },
  { id: 'ts', name: 'TypeScript', icon: 'typescript.svg', category: 'programming language', section: 'Frontend', selected: false, details: 'Typed superset of JavaScript that adds static type definitions for better code quality.', projects: ['AiChat', 'Personaize', 'Sumaplafon', 'Lemiles'] },
  { id: 'svelte', name: 'SvelteKit', icon: 'svelte.svg', category: 'frontend framework', section: 'Frontend', selected: false, details: 'Modern web framework that compiles components to efficient vanilla JavaScript.', projects: [] },
  { id: 'next', name: 'Next.JS', icon: 'nextjs.png', category: 'framework', section: 'Frontend', selected: false, details: '2 years Experience, used for both as a Frontend and Fullstack. familiar with App Router, with integration with Tanstack Query, Zustand, Drizzle ORM, and Docker.', projects: ['AiChat', 'Personaize', 'Sumaplafon', 'Lemiles'] },
  { id: 'react', name: 'React.JS', icon: 'reactjs-square.png', category: 'frontend library', section: 'Frontend', selected: false, details: 'JavaScript library for building user interfaces with component-based architecture.', projects: ['AiChat', 'Proedu', 'Portfolio Ani', 'Vacansearch'] },
  { id: 'zustand', name: 'Zustand', icon: 'zustand.jpeg', category: 'state management', section: 'Frontend', selected: false, details: 'Lightweight state management solution for React applications with minimal boilerplate.', projects: ['AiChat', 'Sumaplafon'] },
  { id: 'tanstack', name: 'Tanstack', icon: 'tanstack.png', category: 'data fetching', section: 'Frontend', selected: false, details: 'Powerful data synchronization library for fetching, caching, and updating server state.', projects: [] },
  { id: 'postgres', name: 'PostgreSQL', icon: 'postgresql.png', category: 'relational database', section: 'Backend', selected: false, details: 'Advanced open-source relational database with robust features and SQL compliance.', projects: ['Personaize', 'Lemiles'] },
  { id: 'mysql', name: 'MySQL', icon: 'mysql.png', category: 'relational database', section: 'Backend', selected: false, details: 'Popular open-source relational database management system for web applications.', projects: ['Energy Logistics', 'Proedu', 'Izistay', 'Sumaplafon'] },
  { id: 'drizzle', name: 'Drizzle', icon: 'drizzle.png', category: 'ORM', section: 'Backend', selected: false, details: 'TypeScript ORM with type-safe database queries and excellent developer experience.', projects: ['Lemiles'] },
  { id: 'docker', name: 'Docker', icon: 'docker.webp', category: 'containerization', section: 'Other Service', selected: false, details: 'Platform for developing, shipping, and running applications using containerization technology.', projects: ['Personaize', 'Sumaplafon', 'Lemiles', 'Vacansearch'] },
  { id: 'nest', name: 'Nest.JS', icon: 'nestjs.png', category: 'backend framework', section: 'Backend', selected: false, details: 'Progressive Node.js framework for building scalable server-side applications with TypeScript.', projects: [] },
  { id: 'expo', name: 'React Expo', icon: 'expo.png', category: 'mobile framework', section: 'Frontend', selected: false, details: 'React Native Framework to create mobile app using React. very helpful since it also provide development build app and other usefull function like OTA update and EAS', projects: ['AiChat', 'Proedu'] },
  { id: 'tailwind', name: 'Tailwind CSS', icon: 'tailwind.png', category: 'CSS framework', section: 'Frontend', selected: false, details: 'Utility-first CSS framework for rapidly building custom user interfaces.', projects: ['AiChat', 'Personaize', 'Lemiles', 'Energy Logistics'] },
  { id: 'framer-motion', name: 'Framer Motion', icon: 'framer-motion.svg', category: 'animation library', section: 'Frontend', selected: false, details: 'React library for building performant and scalable animations and transitions.', projects: [] },
  { id: 'bootstrap', name: 'Bootstrap', icon: 'bootstrap.png', category: 'CSS framework', section: 'Frontend', selected: false, details: 'Popular CSS framework for developing responsive and mobile-first websites.', projects: ['AiChat', 'Sumaplafon', 'Energy Logistics'] },
  { id: 'mantine', name: 'Mantine', icon: 'mantine.png', category: 'UI library', section: 'Frontend', selected: false, details: 'React components library with native dark theme support and flexible customization.', projects: [] },
  { id: 'heroui', name: 'Hero UI', icon: 'hero-ui.webp', category: 'UI library', section: 'Frontend', selected: false, details: 'Modern React UI library with beautiful components and excellent accessibility features.', projects: [] },
  { id: 'laravel', name: 'Laravel', icon: 'laravel.jpeg', category: 'backend framework', section: 'Backend', selected: false, details: 'PHP web application framework with expressive syntax and robust features for web development.', projects: ['AiChat', 'Sumaplafon'] },
  { id: 'ci', name: 'Codeigniter', icon: 'codeigniter.png', category: 'backend framework', section: 'Backend', selected: false, details: 'Lightweight PHP framework with simple configuration and excellent performance.', projects: ['Energy Logistics', 'Proedu', 'Izistay'] },
  { id: 'jquery', name: 'jQuery', icon: 'jquery2.svg', category: 'JavaScript library', section: 'Frontend', selected: false, details: 'Fast and lightweight JavaScript library for DOM manipulation and event handling.', projects: ['Energy Logistics', 'Izistay', 'Proedu'] },
  { id: 'alpine', name: 'Alpine JS', icon: 'alpinejs.png', category: 'JavaScript framework', section: 'Frontend', selected: false, details: 'Minimal framework for composing JavaScript behavior directly in HTML markup.', projects: ['Energy Logistics'] },
  { id: 'socketio', name: 'Socket.IO', icon: 'socket-io.svg', category: 'real-time communication', section: 'Backend', selected: false, details: 'Real-time bidirectional event-based communication library for web applications.', projects: ['AiChat'] },
  { id: 'zod', name: 'zod', icon: 'zod.jpeg', category: 'schema validation', section: 'Backend', selected: false, details: 'TypeScript-first schema validation library with static type inference.', projects: [] },
  { id: 'formik', name: 'Formik', icon: 'formik.png', category: 'form library', section: 'Frontend', selected: false, details: 'React library for building forms with validation, error handling, and field management.', projects: ['AiChat'] },
  { id: 'react-hook-form', name: 'React Hook Form', icon: 'react-hook-form.png', category: 'form library', section: 'Frontend', selected: false, details: 'Performant, flexible forms library with easy validation and minimal re-renders.', projects: ['AiChat'] },
  { id: 'vite', name: 'Vite', icon: 'vite.png', category: 'build tool', section: 'Frontend', selected: false, details: 'Fast build tool and development server with hot module replacement for modern web projects.', projects: ['AiChat', 'Vacansearch'] },
  { id: 'prisma', name: 'Prisma ORM', icon: 'prisma.webp', category: 'ORM', section: 'Backend', selected: false, details: 'Modern database toolkit with type-safe client and intuitive data modeling.', projects: ['Sumaplafon'] },
  { id: 'claude', name: 'Claude (Anthropic)', icon: 'claude.svg', category: 'AI model & coding agent', section: 'AI', selected: false, details: 'Advanced AI assistant by Anthropic. Used via Claude Code as the engineering pair for spec-driven, vibe-engineered development on Vacansearch.', projects: ['Personaize', 'Vacansearch'] },
  { id: 'gemini', name: 'Google Gemini', icon: 'gemini-old.png', category: 'AI model', section: 'AI', selected: false, details: 'Google\'s multimodal AI model for text, image, and code generation tasks.', projects: ['Personaize', 'Energy Logistics', 'Lemiles'] },
  { id: 'deepseek', name: 'Deepseek', icon: 'deepseek.png', category: 'AI model', section: 'AI', selected: false, details: 'Powerful AI model optimized for coding and technical problem-solving tasks.', projects: [] },
  { id: 'vscode', name: 'Visual Studio Code', icon: 'vscode.png', category: 'code editor', section: 'Code Editor', selected: false, details: 'Popular source code editor with rich ecosystem of extensions and integrated terminal.', projects: [] },
  { id: 'cursor', name: 'Cursor', icon: 'cursor.png', category: 'AI-powered editor', section: 'Code Editor', selected: false, details: 'AI-enhanced code editor with intelligent suggestions and automated code generation.', projects: [] },
  { id: 'qoder', name: 'Qoder', icon: 'qoder.png', category: 'AI-powered editor', section: 'Code Editor', selected: false, details: 'Advanced AI-powered development environment with intelligent code assistance and collaboration.', projects: ['Personaize'] },
  { id: 'void', name: 'Void', icon: 'void.png', category: 'code editor', section: 'Code Editor', selected: false, details: 'Minimalist code editor focused on speed and simplicity for efficient coding workflow.', projects: [] },
  { id: 'supabase', name: 'Supabase', icon: 'supabase.jpeg', category: 'BaaS (Backend as a Service)', section: 'Backend', selected: false, details: 'Provides a managed PostgreSQL database and other essential backend tools (authentication, serverless functions, etc)', projects: ['Personaize'] },
  { id: 'neondb', name: 'Neon DB', icon: 'neondb.jpeg', category: 'Cloud Database Service (postgresql)', section: 'Backend', selected: false, details: 'Cloud-native, serverless, fully managed PostgreSQL database service', projects: [] },
  { id: 'firebase', name: 'Firebase', icon: 'firebase2.png', category: 'BaaS (Backend as a Service)', section: 'Backend', selected: false, details: 'Set of backend cloud computing services and application development platforms provided by Google', projects: [] },
  { id: 'github', name: 'Github', icon: 'github.png', category: 'Git', section: 'Other Service', selected: false, details: 'Git platform to store, share, and work together with others to write code', projects: ['AiChat', 'Personaize', 'Proedu', 'Izistay', 'Sumaplafon', 'Lemiles', 'Portfolio Ani', 'Energy Logistics', 'Vacansearch'] },
  { id: 'gitlab', name: 'Gitlab', icon: 'gitlab.png', category: 'Git', section: 'Other Service', selected: false, details: 'Git platform to store, share, and work together with others to write code', projects: ['AiChat'] },
  { id: 'netlify', name: 'Netlify', icon: 'netlify.webp', category: 'Deployment', section: 'Other Service', selected: false, details: 'Fast Static Web Hosting with Continuous Deployment by Vercel', projects: ['Portfolio Ani'] },
  { id: 'cloudflare', name: 'Cloudflare', icon: 'cloudflare.jpg', category: 'CDN', section: 'Other Service', selected: false, details: 'Cloudflare is a global CDN and DDoS protection service.', projects: ['Personaize'] },
  { id: 'nginx', name: 'Nginx', icon: 'nginx.webp', category: 'Web Server', section: 'Other Service', selected: false, details: 'High-performance web server and reverse proxy server.', projects: ['Personaize', 'Sumaplafon', 'Vacansearch'] },
  { id: 'slack', name: 'Slack', icon: 'slack.png', category: 'Team Collaboration', section: 'Other Service', selected: false, details: 'Slack is a communication platform that connects teams and enables them to work together more efficiently.', projects: ['AiChat'] },
  { id: 'clickup', name: 'Clickup', icon: 'clickup.png', category: 'Project Management', section: 'Other Service', selected: false, details: 'All-in-one work management platform that helps teams stay organized and productive.', projects: ['AiChat'] },
  { id: 'ryver', name: 'Ryver', icon: 'ryver.webp', category: 'Team Management', section: 'Other Service', selected: false, details: 'Communication and collaboration platform for teams, similar to Slack.', projects: ['AiChat'] },
  { id: 'openclaw', name: 'Openclaw', icon: 'openclaw.png', category: 'AI', section: 'AI', selected: false, details: 'Personal AI Assistant', projects: [] },
  { id: 'hermes-agent', name: 'Hermes Agent', icon: 'hermes-agent.png', category: 'AI coding agent', section: 'AI', selected: false, details: 'AI-powered coding agent for autonomous software development tasks, code generation, and multi-step engineering workflows.', projects: ['Lemiles'] },
  { id: 'telegram', name: 'Telegram', icon: 'telegram.webp', category: 'Messenger', section: 'Other Service', selected: false, details: 'Messenger platform used to build the Lemiles accountability bot.', projects: ['Lemiles'] },
  { id: 'hono', name: 'Hono.JS', icon: 'hono.webp', category: 'backend framework', section: 'Backend', selected: false, details: 'Ultrafast, lightweight web framework for building APIs on Node.js and the edge. Used as the backend API for Vacansearch.', projects: ['Vacansearch'] },
  { id: 'playwright', name: 'Playwright', icon: 'playwright.webp', category: 'E2E testing & automation', section: 'Other Service', selected: false, details: 'Browser automation and end-to-end testing framework. Powers Vacansearch career-page scanning and scraping.', projects: ['Vacansearch'] },
  { id: 'pnpm', name: 'pnpm Monorepo', icon: 'pnpm.png', category: 'package manager / monorepo', section: 'Other Service', selected: false, details: 'Fast, disk-efficient package manager used to manage the Vacansearch pnpm monorepo workspaces.', projects: ['Vacansearch'] },
  { id: 'vps', name: 'VPS', icon: 'cloudflare.jpg', category: 'hosting / infrastructure', section: 'Other Service', selected: false, details: 'Self-managed Virtual Private Server where apps are deployed and run via Docker — manually, without CI/CD.', projects: ['Vacansearch', 'Personaize', 'Lemiles', 'Sumaplafon'] },
];

// Content
export const content: ContentLabels = {
  myWorks: "My Works",
  contactMe: "Contact Me",
  downloadCV: "Download CV",
  title: "Not just dev. The whole product, end to end.",
  subtitle: "Open to full-time roles & product collaboration",
  name: "Rizkianto Akbar",
  roles: [
    {
      title: "Software Engineer",
      icon: MonitorCog,
      img: 'engineer.png',
    },
    {
      title: "Product Maker",
      icon: Lightbulb,
      img: 'product-maker.png',
    },
    {
      title: "Frontend Dev",
      icon: Gpu,
      img: 'frontend.png',
    },
  ],
  contributed: [
    {
      name: "Vacansearch",
      image: 'vacansearch.svg',
      showcase: 'vacans.png',
      link: 'https://vacansearch.com',
      shortIntro: 'Crawl & Scrape Google Data',
      mainTask: 'Active job search + cold approach companion. Curate target companies, auto-scan their career pages for openings, analyze company fit, and reach out before the applicant pool catches on.',
      buildingCaption: 'Use Google to find companies matching my preferences — small-to-mid tech teams, product companies, remote-friendly — and then crawl into their websites to check for open positions.',
      techStack: ["react", "hono", "playwright", "claude"],
      problem: "I can't find potential job or business to offer my service.",
    },
    // {
    //   name: "Personaized",
    //   image: 'personaized.png',
    //   link: 'https://personaized.com',
    //   shortIntro: 'Resume to Personal Website Generator',
    //   mainTask: 'Enhance your branding by having Personal website. Upload your resume and Instantly generate personal website in one click.',
    //   techStack: ["next", "gemini", "supabase"],
    // },
    {
      name: "Lemiles",
      image: 'lemiles-logo.png',
      showcase: 'lemiles-port.png',
      link: 'https://lemiles.com',
      shortIntro: '100-Day Challenge Buddy Telegram',
      mainTask: 'First AI-native project as sole engineer. Built a Telegram bot powered by Hermes agent framework + Gemini 2.0 Flash where users set a 100-day challenge and receive daily check-ins from a buddy that feels human — with intent detection, missed-day nudges, streak tracking, Google Sheets sync, and a web dashboard.',
      buildingCaption: 'Set a 100-day challenge on Telegram and get daily check-ins from an AI buddy that feels human — it detects missed days, nudges you back on track, and keeps your streak synced to a web dashboard.',
      techStack: ["next", "hermes-agent", "gemini", "telegram"],
    },
    {
      name: "Energy Logistics",
      image: 'enlog-logo.png',
      link: 'https://www.energy-logistics.co.id',
      showcase: 'enlog-port.png',
      shortIntro: 'Logistic solution for B2B',
      mainTask: 'Built a management system that preserves company documents in one place, making the whole process easy to manage, retrieve, and analyze as the business grows.',
      buildingCaption: 'Centralize every company document into one dashboard — replacing scattered spreadsheets and folders — so records stay easy to retrieve and analyze as the business grows.',
      techStack: ["ci", "alpine", "jquery"],
      problem: "As the company grows, documents get scattered and hard to organize.",
    },
    {
      name: "AiChat",
      image: 'aichat-logo.svg',
      link: 'https://aichat.com',
      shortIntro: 'AI Conversation',
      mainTask: 'Built the integration layer inside AiChat that connects one AI agent to WhatsApp, Telegram, Instagram, and more from a single dashboard.',
      techStack: ["next", "expo", "laravel"],
      problem: "Managing your clients across every messenger platform is hard.",
    },
    {
      name: "Izistay",
      image: 'izistay-logo.png',
      link: 'https://www.instagram.com/izi_stay/',
      shortIntro: 'Property Rental',
      mainTask: "Listed it on Izistay's rental platform, where tenants can search, book, and pay online without ever walking past the door.",
      techStack: ["ci", "mysql", "jquery"],
      problem: "I have an empty house, but the location is hard to find.",
    },
    {
      name: "Proedu",
      image: 'proedu-logo.png',
      link: 'https://www.linkedin.com/company/proedu-id',
      shortIntro: 'LSM for Teacher',
      mainTask: 'Built Proedu, an online course platform made specifically for teachers, with curriculum management built in.',
      techStack: ["react", "expo", "ci"],
      problem: "Only a handful of workshops exist for teachers to grow.",
    },
    {
      name: "Sumaplafon",
      image: 'suma-logo.png',
      link: 'https://katalog.sumaplafon.com',
      shortIntro: 'Product Catalouge of Material Shop',
      mainTask: "Built an online catalog with its own management dashboard, so the shop's products stay visible around the clock.",
      techStack: ["next", "docker", "github"],
      problem: "I want my products to be seen by anyone, anywhere.",
    },
    {
      name: "Portfolio - Nharyani",
      image: 'nharyani-logo.png',
      link: 'https://nrharyani.com/',
      shortIntro: 'Personal Portfolio',
      mainTask: 'Being a teacher require to keep learning, this is the platform when teacher can get the lesson to improve themself. Teacher also can manage curriculum for student',
      techStack: ["react"],
    },
  ],
  location: "Indonesia (Bogor)",
  tagline: "Looking to collaborate? Put your request through the form below.",
  agentDescription: "A custom AI will analyze our potential match.",
  storedTagline: "Hello {email}, you still there?",
  storedDescription: "We have analyzed your description before, click 'view' to check it out.",
  writeDescription: "Write description",
  sampleAgentValue: `Describe the role, requirements, and other details about this opportunity...`,
  uploadJobPoster: "Upload job poster",
  pasteLink: "Paste Link",
  requirementPlaceholder: "Paste your requirement here...",
  requirementHelp: "don't know what exactly you are looking for? or you need help to define the requirement? I have created one tools to help you out, check here!",
  analyzeProfile: "Analyze Profile",
  toolsTitle: "The Tools of My Craft",
  toolsSubtitle: "select one or more tools to find out more details",
  projects: "Experience Milestone",
  all: "All",
  companyRoles: "Company & Roles",
  taskResponsibility: "Task & Responsibility",
  portfolio: "Portfolio",
  fulltime: "Fulltime Employee",
  contract: "Contract employee",
  freelance: "Freelance",
  remote: "Remote",
  officialActive: "Official Link (Active)",
  officialInactive: "Official Link (Inactive)",
  tribute: "Tribute",
  nextExperience: "2 years Experience, used for both as a Frontend and Fullstack. familiar with App Router, with integration with Tanstack Query, Zustand, Drizzle ORM, and Docker.",
  shipmentTracking: "SHIPMENT TRACKING"
};